### ISSUE TITLE
parser error on shovel and lonely operators

### ISSUE THREAD

**Issue by d-m-u** [jrafanie/churn_vs_complexity#4]
please do feel free to tell me that this is the wrong place to open this if that is in fact the case:

```/Users/drewmu/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/racc/parser.rb:528:in `on_error': app/models/miq_server/at_startup.rb:27 :: parse error on value "&." (error) (Racc::ParseError)```

```lib/tasks/gettext_task_override.rb:36 :: parse error on value "<<" (tLSHFT) (Racc::ParseError)```

**Comment by jrafanie** [comment]
Sounds like bundle update needs to be done and check in a new lockfile.  I haven't looked at it but I think it should still work as long as the tools support ruby 2.5+.

**Comment by jrafanie** [comment]
This should be fixed now from https://github.com/jrafanie/churn_vs_complexity/commit/67320b218839072788ae91c5da23b2b450232487
